import 'package:drift/drift.dart';

/// Connected Cospend projects saved on this device.
/// Password not stored in bd, it's on secure storage instead
class Projects extends Table {
  /// Local id generated by the app (uuid/string).
  TextColumn get id => text()();

  /// Project name fetched from API (null until we fetch it).
  TextColumn get name => text().nullable()();

  /// Base server URL (e.g. https://cloud.website.xyz).
  TextColumn get serverUrl => text()();

  /// Public project token from the share link /s/<token>.
  TextColumn get projectId => text()();

  @override
  Set<Column> get primaryKey => {id};

  /// Prevent duplicates: same server + same token.
  /// NOTE: Drift will snake_case columns in SQL.
  @override
  List<String> get customConstraints => [
        'UNIQUE(server_url, project_id)',
      ];
}

/// Cached members for each project.
/// We keep it minimal: member id + member name.
class Members extends Table {
  /// Local row id. Simple stable format: "<projectLocalId>:<remoteMemberId>".
  TextColumn get id => text()();

  /// Link to Projects.id (local project id).
  TextColumn get projectLocalId => text()();

  /// Member id inside Cospend (remote id).
  IntColumn get remoteMemberId => integer()();

  /// Display name (used in UI).
  TextColumn get name => text()();

  @override
  Set<Column> get primaryKey => {id};

  /// Prevent duplicates for the same project.
  @override
  List<String> get customConstraints => [
        'UNIQUE(project_local_id, remote_member_id)',
      ];
}